name: Ross Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export APPS_JSON='[ \
            { \
              "url": "https://github.com/frappe/payments", \
              "branch": "develop" \
            }, \
            { \
              "url": "https://github.com/frappe/erpnext", \
              "branch": "version-14" \
            }, \
            { \
              "url": "https://github.com/frappe/hrms", \
              "branch": "version-14" \
            }, \
          ]'
          export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)
          echo "content=$APPS_JSON_BASE64" >> $GITHUB_ENV
      - run: echo ${{ env.APPS_JSON_BASE64 }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: rosschiubsol
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}

      - name: build docker and push
        run: |
          /usr/bin/docker buildx build \
          --build-arg FRAPPE_PATH=https://github.com/frappe/frappe \
          --build-arg FRAPPE_BRANCH=version-14 \
          --build-arg PYTHON_VERSION=3.10.5 \
          --build-arg NODE_VERSION=16.18.0 \
          --build-arg APPS_JSON_BASE64=$APPS_JSON_BASE64 \
          --platform linux/amd64,linux/arm64 --tag rosschiubsol/custom-erpnext:14.latest --file ./images/custom/Containerfile --push .
